kind: pipeline
type: docker
name: default
steps:
  - name: test
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -t hc-docker.sophia.local/matsubara/linebot:1.3 /drone/src
      - docker tag hc-docker.sophia.local/matsubara/linebot:1.3 hc-docker.sophia.local/matsubara/linebot:latest
      - docker push hc-docker.sophia.local/matsubara/linebot:1.3
      - docker push hc-docker.sophia.local/matsubara/linebot:latest

  - name: notify
    image: plugins/webhook
    settings:
      urls: https://outlook.office.com/webhook/e2d69b49-9681-4767-a03e-4883174fae64@ecc17227-84d3-492b-a8a6-4774fd6c62f2/IncomingWebhook/63da66c252014c8e91d22272cfbeca47/b230c44f-7766-42cf-9254-9405b1adfd61
      content_type: application/json
      template: |
        {
          "title": "matsubara",
          "text": "Line bot container test",
        }

  - name: deploy to production
    image: appleboy/drone-ssh
    settings:
      host: 192.168.0.30
      username: hcadmin
      password: hcadmin
      port: 22
      script:
        - docker pull hc-docker.sophia.local/matsubara/linebot:latest
        - docker-compose -f /mnt/samba/oc7/docker-compose.yml build bot
        - docker-compose -f /mnt/samba/oc7/docker-compose.yml up -d bot

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

