kind: pipeline
type: docker
name: default
steps:
  - name: test
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -t %%/matsubara/linebot:1.5 /drone/src
      - docker tag %%/matsubara/linebot:1.5 %%/matsubara/linebot:latest
      - docker push %%/matsubara/linebot:1.5
      - docker push %%/matsubara/linebot:latest

  - name: notify
    image: plugins/webhook
    settings:
      urls: https://outlook.office.com/webhook/webhoksecret
      content_type: application/json
      template: |
        {
          "title": "matsubara",
          "text": "Line bot container test",
        }

  - name: deploy to production
    image: appleboy/drone-ssh
    settings:
      host: localhost
      username: username
      password: password
      port: port
      script:
        - docker pull %%/matsubara/linebot:latest
        - docker-compose -f /path/docker-compose.yml build bot
        - docker-compose -f /path/docker-compose.yml up -d bot

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

